"""stage4

Revision ID: 1862fccbc243
Revises: 7f12ea499f4e
Create Date: 2021-10-06 22:05:58.734375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1862fccbc243'
down_revision = '7f12ea499f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
