"""stage10

Revision ID: 25bc0c962e22
Revises: f625d5cf3d1f
Create Date: 2021-10-07 14:25:07.211397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bc0c962e22'
down_revision = 'f625d5cf3d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keyword', 'keyword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keyword', sa.Column('keyword', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
