"""stage2

Revision ID: 4b74f70e9d56
Revises: c234ba9b54d4
Create Date: 2021-10-06 21:10:59.152870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b74f70e9d56'
down_revision = 'c234ba9b54d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('link', sa.String(length=50), nullable=False))
    op.alter_column('author', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('author', 'author_info',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'author_info',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('author', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('author', 'link')
    # ### end Alembic commands ###
