"""stage14

Revision ID: 72022a847c53
Revises: 859aa0a8c66c
Create Date: 2021-10-07 15:33:06.697385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72022a847c53'
down_revision = '859aa0a8c66c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
