"""stage12

Revision ID: 859aa0a8c66c
Revises: f0157b91831d
Create Date: 2021-10-07 14:31:15.416782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859aa0a8c66c'
down_revision = 'f0157b91831d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keywords_and_quotes', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keywords_and_quotes', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
