"""init

Revision ID: c234ba9b54d4
Revises: 
Create Date: 2021-10-06 17:53:15.474963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c234ba9b54d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('author_info', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_table('keyword',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('keyword_id')
    )
    op.create_table('quote',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('quote_id')
    )
    op.create_table('association',
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.keyword_id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.quote_id'], ),
    sa.PrimaryKeyConstraint('keyword_id', 'quote_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('quote')
    op.drop_table('keyword')
    op.drop_table('author')
    # ### end Alembic commands ###
