"""stage6

Revision ID: eff1ac91729f
Revises: 464bd0f405d6
Create Date: 2021-10-06 23:29:02.878762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff1ac91729f'
down_revision = '464bd0f405d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
