"""stage9

Revision ID: f625d5cf3d1f
Revises: f78603f88754
Create Date: 2021-10-07 12:57:37.485279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f625d5cf3d1f'
down_revision = 'f78603f88754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
